name: reviwo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=1.41.5=h5eee18b_0
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.4=h6a678d5_0
  - openssl=3.3.1=h4bc722e_2
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiohttp-cors==0.7.0
      - aiorwlock==1.4.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bayesian-optimization==1.5.1
      - blessed==1.20.0
      - cachetools==5.4.0
      - cairocffi==1.7.1
      - cairosvg==2.5.2
      - causal-learn==0.1.3.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colorful==0.5.6
      - colour==0.1.5
      - contourpy==1.2.1
      - cssselect2==0.7.0
      - cycler==0.12.1
      - cython==3.0.0a10
      - defusedxml==0.7.1
      - distlib==0.3.8
      - dtreeviz==1.4.0
      - einops==0.8.0
      - etils==1.7.0
      - exceptiongroup==1.2.2
      - farama-notifications==0.0.4
      - fastapi==0.1.17
      - fasteners==0.19
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - glfw==2.7.0
      - google-api-core==2.19.1
      - google-auth==2.32.0
      - googleapis-common-protos==1.63.2
      - gpustat==1.1.1
      - grpcio==1.65.1
      - gym==0.25.0
      - gym-notices==0.0.8
      - gymnasium==1.0.0a2
      - h11==0.14.0
      - h5py==3.11.0
      - httptools==0.6.1
      - idna==3.7
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - loguru==0.7.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - metaworld==2.0.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mujoco==2.3.7
      - mujoco-py==2.1.2.14
      - multidict==6.0.5
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.1
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - packaging==24.1
      - pandas==2.2.2
      - patsy==0.5.6
      - pillow==10.4.0
      - platformdirs==3.11.0
      - pluggy==1.5.0
      - pot==0.9.4
      - prettytable==3.10.2
      - prometheus-client==0.13.1
      - proto-plus==1.24.0
      - protobuf==4.25.4
      - psutil==6.0.0
      - py-spy==0.3.14
      - pyarmor==8.4.6
      - pyarmor-cli-core==5.4.3
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydot==3.0.1
      - pynvml==11.5.3
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pypdf2==1.26.0
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-graphviz==0.20.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - ray==2.9.0
      - referencing==0.35.1
      - requests==2.32.3
      - revive==1.0.0
      - rpds-py==0.19.1
      - rsa==4.9
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - setuptools==64.0.3
      - six==1.16.0
      - smart-open==7.0.4
      - sniffio==1.3.1
      - starlette==0.38.2
      - statsmodels==0.14.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch==2.1.0
      - tqdm==4.66.4
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - uvicorn==0.30.3
      - uvloop==0.19.0
      - virtualenv==20.21.0
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websockets==12.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - wurlitzer==3.1.1
      - yarl==1.9.4
      - zipp==3.19.2
      - zoopt==0.4.2
prefix: /opt/conda/envs/revive
